/**
 * Subsets Ionicons to the icons this app actually names.
 *
 * The vendored Ionicons TTF is 380 KB — the single largest asset the
 * site serves, larger than the JavaScript bundle after compression, and
 * fetched on every page because icons are everywhere. The app names a
 * few dozen of its ~1,300 glyphs.
 *
 * The names are read out of the source rather than maintained by hand,
 * so this cannot drift: any string literal that is a valid Ionicons
 * glyph name counts. `src/constants/iconSubset.ts` records what was found,
 * and a test fails if the source names something the subset does not
 * carry.
 *
 * Run after adding an icon:  node scripts/subset-icons.mjs
 * Requires fontTools (pip install fonttools brotli) — the output is
 * committed, so this is an occasional step, not part of the build.
 */
import { execFileSync } from 'node:child_process';
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = new URL('..', import.meta.url).pathname;
const GLYPH_MAP = join(
  ROOT,
  'node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/glyphmaps/Ionicons.json'
);
const FONT = join(
  ROOT,
  'node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/Fonts/Ionicons.ttf'
);
const OUT_FONT = join(ROOT, 'assets/fonts/ionicons-subset.woff2');
const OUT_LIST = join(ROOT, 'src/constants/iconSubset.ts');

const glyphMap = JSON.parse(readFileSync(GLYPH_MAP, 'utf8'));

/** Every .ts/.tsx under src, tests included — they name icons too. */
function sources(dir) {
  return readdirSync(dir).flatMap((entry) => {
    const path = join(dir, entry);
    if (statSync(path).isDirectory()) return sources(path);
    return /\.tsx?$/.test(path) ? [path] : [];
  });
}

const used = new Set();
for (const file of sources(join(ROOT, 'src'))) {
  const text = readFileSync(file, 'utf8');
  for (const [, name] of text.matchAll(/['"`]([a-z][a-z0-9-]{2,})['"`]/g)) {
    if (name in glyphMap) used.add(name);
  }
}

const names = [...used].sort();
const codepoints = names.map((name) => glyphMap[name]);

execFileSync('pyftsubset', [
  FONT,
  `--unicodes=${codepoints.map((c) => `U+${c.toString(16)}`).join(',')}`,
  '--flavor=woff2',
  '--no-hinting',
  `--output-file=${OUT_FONT}`,
]);

writeFileSync(
  OUT_LIST,
  `// Generated by scripts/subset-icons.mjs — do not edit by hand.
//
// The Ionicons glyphs carried by assets/fonts/ionicons-subset.woff2.
// An icon named in the source but missing here renders as a blank box,
// which is why a test compares the two.

export const SUBSET_ICONS = [
${names.map((name) => `  '${name}',`).join('\n')}
] as const;

export type SubsetIcon = (typeof SUBSET_ICONS)[number];
`
);

const before = statSync(FONT).size;
const after = statSync(OUT_FONT).size;
console.log(
  `${names.length} icons: ${Math.round(before / 1024)} KB TTF -> ${Math.round(
    after / 1024
  )} KB woff2`
);
